/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Main;

import Controlador.Controlador;
import static Controlador.Controlador.Eliminar;
import static Controlador.Controlador.escribirDocu;
import static Controlador.Controlador.mostrarCoches;
import static Controlador.Controlador.mostrarMotos;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import misExcepciones.misExcepciones;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class BorrarVehículoPorTipo extends javax.swing.JDialog {

    String tipo;
    /**
     * Creates new form BorrarVehículoPorTipo
     */
    public BorrarVehículoPorTipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Añado dos opciones en la ComboBox
        jComboBox1Tipo.addItem("1");
        jComboBox1Tipo.addItem("2");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jComboBox1Tipo = new javax.swing.JComboBox<>();
        jButton1OK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1Eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrar Vehículo");
        setBackground(new java.awt.Color(242, 27, 242));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Elige un tipo y pulsa ok (1. coche / 2. moto):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabel1, gridBagConstraints);

        jComboBox1Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1TipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBox1Tipo, gridBagConstraints);

        jButton1OK.setText("OK");
        jButton1OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        getContentPane().add(jButton1OK, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(22, 89));
        jTextArea1.setSize(new java.awt.Dimension(272, 89));
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Escribe la matrícula del vehículo que quieres borrar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabel2, gridBagConstraints);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 27, 30, 24);
        getContentPane().add(jTextField1, gridBagConstraints);

        jButton1Eliminar.setText("Eliminar");
        jButton1Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 27, 30, 24);
        getContentPane().add(jButton1Eliminar, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Los vehiculos del tipo señalados son:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 20);
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1TipoActionPerformed
        // TODO add your handling code here:
        tipo = (String)jComboBox1Tipo.getSelectedItem(); //Casteo lo selecionado en la casialla a String
    }//GEN-LAST:event_jComboBox1TipoActionPerformed

    private void jButton1OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OKActionPerformed
        // En caso de selecionar 1 muestro coches, si no mestro motos
        if(tipo == "1"){
            jTextArea1.setText(mostrarCoches());
        }else{
            jTextArea1.setText(mostrarMotos());
        }
    }//GEN-LAST:event_jButton1OKActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton1EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EliminarActionPerformed
        // TODO add your handling code here:
        String matricula = jTextField1.getText(); //Creo variable para darle el valor de la cailla
        
        // Controlo que la matricula escrita coincida con las almacenadas, si es así borro el vehículo
        if(Controlador.obtenerVehiculos().containsKey(matricula)){
            System.out.println("el vehiculo selecionado es: "+matricula);   //Esto era para verlo yo por consola en las pruebas
        
            
           Eliminar(matricula);
            
        //Escribo los cambios realizados (Podría solo hacerlo cuando se ciere la aplicación, pero bueno, por si acaso hay algún fallo antes de apagar
        //Muestro un panel de confirmación de vehículo borrado
        try {
                escribirDocu();
                JOptionPane.showMessageDialog(this, "Vehiculo eliminado", "Vehículo eliminado", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException e) {
                System.out.println("Documento no encontrado.");
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la base de datos", "Error de almacenaje", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la base de datos", "Error de almacenaje", JOptionPane.INFORMATION_MESSAGE);
            }
        
        // Esto ra para verlo yo por consola
            System.out.println("caso 1");
            System.out.println(Controlador.obtenerVehiculos().values().toString());
            
            System.out.println("caso2");
        mostrarCoches();
        dispose(); //Cierro el dialogo
        }else{  //En caso de que la matrícula esté mal escrita avisa al usuario para que la modifíque con un panel
            JOptionPane.showMessageDialog(this, "No escribiste correctamente la matrícula", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
        }
        
       
    }//GEN-LAST:event_jButton1EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarVehículoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarVehículoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarVehículoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarVehículoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BorrarVehículoPorTipo dialog = new BorrarVehículoPorTipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Eliminar;
    private javax.swing.JButton jButton1OK;
    private javax.swing.JComboBox<String> jComboBox1Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
