/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Main;

import static Controlador.Controlador.escribirDocu;
import static Controlador.Controlador.ingresarVehículo;
import static Controlador.Controlador.mostrarCoches;
import static Controlador.Controlador.recorrerVehiculos;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import misExcepciones.misExcepciones;
import modelo.Vehiculo;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class IngresarVehiculo extends javax.swing.JDialog {

    
    String matricula;
    String modelo;
    String marca;
    int cilindrada;
    double precio2;
    int tipo;
    ArrayList<String> componentes;

    /**
     * Creates new form IngresarVehiculo
     */
    public IngresarVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        okBotonOK = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modeloTexto = new javax.swing.JTextField();
        MarcaTexto = new javax.swing.JTextField();
        precioTexto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SpinnerCilindrada = new javax.swing.JSpinner();
        jSpinner1Tipo = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1Cuero = new javax.swing.JCheckBox();
        jCheckBox2Airbag = new javax.swing.JCheckBox();
        jCheckBox3Altavoces = new javax.swing.JCheckBox();
        jCheckBox4Llave = new javax.swing.JCheckBox();
        jCheckBox5Garantia = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo ingreso");
        setBackground(new java.awt.Color(242, 27, 242));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        okBotonOK.setText("OK");
        okBotonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(okBotonOK, gridBagConstraints);

        jButton2Cancelar.setText("CANCEL");
        jButton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButton2Cancelar, gridBagConstraints);

        jLabel1.setText("Ingrese la matrícula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 15);
        getContentPane().add(textoMatricula, gridBagConstraints);

        jLabel2.setText("Ingrese el modelo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Ingrese la marca:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Ingrese la cilindrada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Ingrese el precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(modeloTexto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(MarcaTexto, gridBagConstraints);

        precioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTextoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(precioTexto, gridBagConstraints);

        jLabel6.setText("Tipo (1. coche  /  2. moto):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel6, gridBagConstraints);

        SpinnerCilindrada.setModel(new javax.swing.SpinnerNumberModel(200, 0, 5000, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(SpinnerCilindrada, gridBagConstraints);

        jSpinner1Tipo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jSpinner1Tipo, gridBagConstraints);

        jLabel7.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel7, gridBagConstraints);

        jCheckBox1Cuero.setText("Tapicería de cuero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jCheckBox1Cuero, gridBagConstraints);

        jCheckBox2Airbag.setText("Airbag trasero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jCheckBox2Airbag, gridBagConstraints);

        jCheckBox3Altavoces.setText("Altavoes surround");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jCheckBox3Altavoces, gridBagConstraints);

        jCheckBox4Llave.setText("Llave electrónica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jCheckBox4Llave, gridBagConstraints);

        jCheckBox5Garantia.setText("Garantía Premium");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jCheckBox5Garantia, gridBagConstraints);

        jLabel8.setText("Elige los complementos que tiene:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBotonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotonOKActionPerformed

        matricula = textoMatricula.getText();
        modelo = modeloTexto.getText();
        marca = MarcaTexto.getText();
        cilindrada = (int) SpinnerCilindrada.getValue();
        tipo = (int) jSpinner1Tipo.getValue();
        String precio;
        boolean ok = true;

        if (matricula.isEmpty() || modelo.isEmpty() || marca.isEmpty() || cilindrada < 0) { //Si alguno de los campos está vacío muesto mensaje de error

            JOptionPane.showMessageDialog(this, "No se puede dejar campos en blanco", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
        } else {
            
            /*
            Compruebo que en el campo de precio se haya introducido un numero mayor que cero, si no hago un bucle hasta que así sea.
            Si introduce letras salta una excepción y salta una ventana que te avisa de ello
            */
            do {    
                precio = precioTexto.getText();
                try {
                    precio2 = Double.parseDouble(precio);
                    if (precio2 > 0) {
                        ok = false;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "El precio debe de ser un numero", "Error de tipo de dato.", JOptionPane.WARNING_MESSAGE);
                    return;     //Voy al final 
                }
            } while (ok);

            /*
            Creo un Array list para al macenar los distitnos componentes (He decidido hacerlo así para que sea predeterminado
            y no se escriba cualquier componente que tiene por que existir.
            */
            componentes = new ArrayList<>();

            //Estructura condicional para añadir los distintos componentes seleccionados al arraylist
            if (jCheckBox1Cuero.isSelected()) {
                componentes.add("Tapizado de cuero");
            }
            if (jCheckBox2Airbag.isSelected()) {
                componentes.add("Airbags traseros");
            }
            if (jCheckBox3Altavoces.isSelected()) {
                componentes.add("Equipo de sonido Surround");
            }
            if (jCheckBox4Llave.isSelected()) {
                componentes.add("Llave electónica");
            }
            if (jCheckBox5Garantia.isSelected()) {
                componentes.add("Garantía Premium");
            }

            //Relleno el objeto vehiculo con los distintos datos introducidos
            Vehiculo v = new Vehiculo(marca, modelo, cilindrada, componentes, precio2, tipo);
            
            //Llamo a la funcion ingresarvehiculo del controlador para añdir el vehículo al hasmap
            try {
                ingresarVehículo(matricula, v);
            } catch (misExcepciones ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en alta", JOptionPane.ERROR_MESSAGE);;
            }

            //Finalmente escribo todo en el archivo para que se quede guardado y poder recuperarlo en la siguiente vez que inicie la aplicación
            try {
                escribirDocu();
                JOptionPane.showMessageDialog(this, "Vehiculo agregado", "Vehículo agregado", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException e) {
                System.out.println("Documento no encontrado.");
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la base de datos", "Error de almacenaje", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la base de datos", "Error de almacenaje", JOptionPane.INFORMATION_MESSAGE);
            }

//        mostrarTodosLosVehiculos();
            dispose();

        }


    }//GEN-LAST:event_okBotonOKActionPerformed

    private void precioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTextoActionPerformed

    private void jButton2CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelarActionPerformed
        /*
        En caso de que el usuario quera salir del jdialog
        */
        dispose();
    }//GEN-LAST:event_jButton2CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarVehiculo dialog = new IngresarVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MarcaTexto;
    private javax.swing.JSpinner SpinnerCilindrada;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JCheckBox jCheckBox1Cuero;
    private javax.swing.JCheckBox jCheckBox2Airbag;
    private javax.swing.JCheckBox jCheckBox3Altavoces;
    private javax.swing.JCheckBox jCheckBox4Llave;
    private javax.swing.JCheckBox jCheckBox5Garantia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1Tipo;
    private javax.swing.JTextField modeloTexto;
    private javax.swing.JButton okBotonOK;
    private javax.swing.JTextField precioTexto;
    private javax.swing.JTextField textoMatricula;
    // End of variables declaration//GEN-END:variables
}
